cameras:
  alpha_camera:
    type: realsense
    serial_no: "_145422071857"
    activate: true 
    enable_depth: true
    enable_infra: true # think to activate it in addition to infra1 or 2
    enable_infra1: true
    enable_infra2: true 
    enable_color: true
    enable_gyro: false
    enable_accel: false 
    enable_rgbd: false
    pointcloud: true
    enable_sync: false
    align_depth: false

  bravo_camera:
    type: realsense
    serial_no: "_031522071313"
    activate: true
    enable_depth: true
    enable_infra: true # think to activate it in addition to infra1 or 2
    enable_infra1: true
    enable_infra2: true 
    enable_color: true
    enable_gyro: false
    enable_accel: false 
    enable_rgbd: false
    pointcloud: true

  charlie_camera:
    type: realsense
    serial_no: "_143122078418"
    activate: true
    enable_depth: true
    enable_infra: true # think to activate it in addition to infra1 or 2
    enable_infra1: true
    enable_infra2: true 
    enable_color: true
    enable_gyro: false
    enable_accel: false 
    enable_rgbd: false
    pointcloud: true

  echo_camera:
    type: "femto-mega"
    activate: true
    ip: "192.168.1.10"
    port: "8090"
    sync_mode: "standalone"
    enable_colored_point_cloud: true
    depth_registration: true

  foxtrot_camera:
    type: "femto-mega"
    activate: true
    ip: "192.168.1.12"
    port: "8090"
    sync_mode: "standalone"
    enable_colored_point_cloud: true
    depth_registration: true
  
  golf_camera:
    type: "femto-mega"
    activate: true
    ip: "192.168.1.11"
    port: "8090"
    sync_mode: "standalone"
    enable_colored_point_cloud: true
    depth_registration: true
  
