- type: 'femto-mega'
  name_prefix: echo
  bounding_box: &orbbec_size
    width: 0.40
    height: 0.35
  pose:
    x: 0.164756
    y: 0.61793
    z: 0.727701
    roll:  -2.526
    pitch: 0.063
    yaw:   2.469
  fixture_orientation: "+y"
  offset: # From fixture tip to camera optical frame offset
    x: 0.00
    y: 0.00
    z: 0.00

- type: 'femto-mega'
  name_prefix: foxtrot
  bounding_box: *orbbec_size
  pose:
    x: -0.622808
    y: 0.582085
    z: 0.728005
    roll:  -2.414
    pitch: -0.017
    yaw:   -2.494
  fixture_orientation: "+y"
  offset: # From fixture tip to camera optical frame offset
    x: 0.00
    y: 0.00
    z: 0.00

- type: 'femto-mega'
  name_prefix: golf
  bounding_box: *orbbec_size
  pose:
    x: -0.220848
    y: -0.621937
    z: 0.688742
    roll:  -2.552
    pitch: 0.000
    yaw:   -0.015
  fixture_orientation: "-y"
  offset: # From fixture tip to camera optical frame offset
    x: 0.00
    y: 0.00
    z: 0.00
