- type: 'realsense-d435i'
  name_prefix: bravo
  bounding_box: &realsense_size
    width: 0.35
    height: 0.30
  pose:
    x: -0.192736
    y: 0.835309
    z: 0.700992
    roll:  -2.227
    pitch: 0.011
    yaw:   3.142
  fixture_orientation: "+y"
  offset: # From fixture tip to camera optical frame offset
    x: 0.00
    y: 0.00
    z: 0.00

- type: 'realsense-d435i'
  name_prefix: charlie
  bounding_box: *realsense_size
  pose:
    x: -0.670188
    y: -0.558114
    z: 0.597616
    roll:  -2.355
    pitch: -0.100
    yaw:   -0.517
  fixture_orientation: "-y"
  offset: # From fixture tip to camera optical frame offset
    x: 0.00
    y: 0.00
    z: 0.00

- type: 'realsense-d435i'
  name_prefix: alpha
  bounding_box: *realsense_size
  pose:
    x: 0.131421
    y: -0.626980
    z: 0.818875
    roll:  -2.467
    pitch: 0.026
    yaw:   0.475
  fixture_orientation: "-y"
  offset: # From fixture tip to camera optical frame offset
    x: 0.00
    y: 0.00
    z: 0.00

# Soon for orbbec
- type: 'realsense-d435i'
  name_prefix: orbbec
  bounding_box: *realsense_size
  pose:
    x: -0.255
    y: -0.70
    z: 0.68
    roll:  0
    pitch: 0
    yaw:   0
  fixture_orientation: "-y"
  offset: # From fixture tip to camera optical frame offset
    x: 0.00
    y: 0.07
    z: 0.00